name: Build Extras
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "lua/kanagawa-paper/extras/**"
      - "lua/kanagawa-paper/themes/**"
      - "lua/kanagawa-paper/lib/**"
      - "lua/kanagawa-paper/colors.lua"
      - "lua/scripts/**"
jobs:
  extras:
    name: Build Extras
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Set permissions
        run: chmod +x scripts/build.sh
      - name: Run build script
        run: |
          scripts/build.sh || { echo "❌ Build script failed!"; exit 1; }
          git add -f extras/
      - name: Stash changes if needed
        run: |
          git stash push || echo "No changes to stash"
      - name: Pull latest changes with rebase
        run: |
          git pull --rebase origin HEAD
      - name: Restore stash if needed
        run: |
          git stash pop || echo "No changes to restore"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build(extras): auto build themes for extras"
