name: Label Issues
on:
  issues:
    types: [opened]
permissions:
  contents: read
jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: read
      contents: read
    strategy:
      matrix:
        template: [1-bug-report.yml, 2-feature-request.yml]
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}
      - name: Set labels based on policy
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}
