name: panvimdoc
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "README.md"
jobs:
  docs:
    name: pandoc to vimdoc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: kanagawa-paper.nvim
          pandoc: "README.md"
          version: "NVIM v0.8.0"
          toc: true
          description: ""
          demojify: true # Strip emojis from the vimdoc
          dedupsubheadings: false # Add heading to subheading anchor links to ensure that subheadings are unique
          treesitter: true # Use treesitter for highlighting codeblocks
          ignorerawblocks: true # Ignore raw html blocks in markdown when converting to vimdoc
          docmapping: false # Use h4 headers as mapping docs
          docmappingprojectname: true # Use project name in tag when writing mapping docs
          shiftheadinglevelby: 0 # Shift heading levels by specified number
          incrementheadinglevelby: 0 # Increment heading levels by specified number
      - name: Stash changes if needed
        run: |
          git stash push || echo "No changes to stash"
      - name: Pull latest changes with rebase
        run: |
          git pull --rebase origin HEAD
      - name: Restore stash if needed
        run: |
          git stash pop || echo "No changes to restore"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(vim): auto generate vimdoc"
